### ISSUE TITLE
Форматирование

### ISSUE THREAD

**Issue by banyrule** [AishSI/Gun-angle#3]
https://github.com/AishSI/Gun-angle/blob/2003909d7912b9ad0f5a6452f726253e4daea9f5/AngryBirdsTask.cs#L18

Две части выражение "прилипли" в оператору деления `/`
Чтобы не думать о форматировании, можешь использовать clean-up или автоматическое форматирование. CTRL-ALT-L в визуалке, кажется.

**Comment by AishSI** [comment]
Позже нашел эту штуку: Форматирование документа - Ctrl+E,D 
Правда, ощущение, что не всегда срабатывает. пригляжусь еще.
